# -*- coding: utf-8 -*-
"""
Created on Wed Mar 20 01:31:09 2019

@author: Aryan Singh
"""

'''
Basic sampling for AI and statistics

'''
import random
def rejection_sampling(samples, prob, probC,l2):        
    for i in  range(0,samples):
            s = random.random()
            if s < probC:
                if s < (prob): # these samples have rain = true
                    l2.append(1)
                else:
                    l2.append(0)
            else:
                l2.append(0)
    sum=0
    for i in range(0,len(l2)):
        sum+=l2[i]
    sum = sum/len(l2)
    return sum


print('REJECTION - should be similar to ' + str(0.367))
print(rejection_sampling(100,0.3, 0.564,[]))
print(rejection_sampling(100,0.3, 0.564,[]))
print("These are random values generated by random.random()")